title: HUX
email: hillary@hux.com
description: "Provider service announcements"
baseurl: ""
url: "psa.hux.com"
twitter_username: huxatl
github_username:  jamesloper

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:title
